// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfxSnr-vy516ldDPXuOLTwmmqMILQygHo',
    appId: '1:525225209804:web:6a48286c2fc9fdc267f769',
    messagingSenderId: '525225209804',
    projectId: 'provitask-197ff',
    authDomain: 'provitask-197ff.firebaseapp.com',
    storageBucket: 'provitask-197ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Cdr9OS2-YvLrrru7_e0kPlcofkawjR0',
    appId: '1:525225209804:android:8373c7dc6360cc0267f769',
    messagingSenderId: '525225209804',
    projectId: 'provitask-197ff',
    storageBucket: 'provitask-197ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfxPhd9sErVNRckpZwaNuUbbz1jU_J2-o',
    appId: '1:525225209804:ios:9f79660eee87408c67f769',
    messagingSenderId: '525225209804',
    projectId: 'provitask-197ff',
    storageBucket: 'provitask-197ff.appspot.com',
    iosClientId: '525225209804-vjo3hgbdl8dkdqplc8oikhf9rs1akcfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.provitaskApp',
  );
}
